[versions]
agp = "8.2.2"
kotlin = "1.9.22"
core-ktx = "1.13.1"
jna = "5.14.0"
cargoNdk = "0.3.4"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }

[plugins]
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
cargoNdk = { id = "com.github.willir.rust.cargo-ndk-android", version.ref = "cargoNdk" }
